language: objective-c
os: osx
osx_image: xcode8
#xcode_project: ios-ci-sample.xcodeproj
#xcode_scheme: ios-ci-sample
script:
  - xcodebuild test -scheme ios-ci-sample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=10.0' -derivedDataPath ./derived-data
  - bundle exec ruby ./test.rb
